import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { invoiceAPI } from '../../services/api';
import { ArrowLeft, Printer } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

export default function InvoiceDetail() {
  const { id } = useParams();
  const [invoice, setInvoice] = useState(null);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();
  const { user } = useAuth();

  useEffect(() => {
    invoiceAPI.getById(id).then(res => setInvoice(res.data.data)).finally(() => setLoading(false));
  }, [id]);

  if (loading) return <div className="flex items-center justify-center h-screen"><div className="w-10 h-10 border-4 border-primary-400 border-t-transparent rounded-full animate-spin" /></div>;
  if (!invoice) return <div className="p-8 text-red-500">Invoice not found</div>;

  return (
    <div className="p-8">
      <div className="flex items-center justify-between mb-6">
        <button onClick={() => navigate('/invoices')} className="flex items-center gap-2 text-indigo-400 hover:text-indigo-600 text-sm font-medium transition-colors">
          <ArrowLeft size={16} /> Back to Invoices
        </button>
        <button onClick={() => window.print()} className="btn-secondary flex items-center gap-2">
          <Printer size={16} /> Print
        </button>
      </div>

      <div className="card max-w-3xl mx-auto" id="invoice-print">
        {/* Header */}
        <div className="flex justify-between items-start mb-10">
          <div>
            <h1 className="font-display text-3xl font-bold text-indigo-900">INVOICE</h1>
            <p className="text-gray-400 text-sm mt-1">#{invoice.invoiceId}</p>
          </div>
          <div className="text-right">
            <p className="font-display font-bold text-lg text-indigo-900">{user?.name}</p>
            <p className="text-sm text-gray-400">Date: {invoice.date}</p>
          </div>
        </div>

        {/* Bill To */}
        <div className="mb-8">
          <p className="text-xs font-semibold text-indigo-300 uppercase tracking-wider mb-2">Bill To</p>
          <p className="font-semibold text-indigo-900">{invoice.customer?.name}</p>
          <p className="text-sm text-gray-500">{invoice.customer?.email}</p>
          <p className="text-sm text-gray-500">{invoice.customer?.phone}</p>
          <p className="text-sm text-gray-500">{invoice.customer?.address}</p>
        </div>

        {/* Items */}
        <div className="overflow-hidden rounded-xl border border-indigo-50 mb-6">
          <table className="w-full text-sm">
            <thead>
              <tr className="table-header">
                <th className="px-4 py-3 text-left">Product</th>
                <th className="px-4 py-3 text-right">Unit Price</th>
                <th className="px-4 py-3 text-right">Qty</th>
                <th className="px-4 py-3 text-right">Subtotal</th>
              </tr>
            </thead>
            <tbody>
              {invoice.items?.map((item, i) => (
                <tr key={i} className="border-t border-indigo-50">
                  <td className="px-4 py-3 font-medium text-indigo-900">{item.product?.name}</td>
                  <td className="px-4 py-3 text-right text-gray-600">${Number(item.price).toFixed(2)}</td>
                  <td className="px-4 py-3 text-right text-gray-600">{item.quantity}</td>
                  <td className="px-4 py-3 text-right font-semibold text-indigo-900">${(Number(item.price) * item.quantity).toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Total */}
        <div className="flex justify-end">
          <div className="w-64">
            <div className="flex justify-between py-3 border-t border-indigo-100">
              <span className="font-bold text-indigo-900">Total Amount</span>
              <span className="font-display text-xl font-bold text-emerald-600">${Number(invoice.totalAmount).toFixed(2)}</span>
            </div>
          </div>
        </div>

        <div className="mt-10 pt-6 border-t border-indigo-50 text-center">
          <p className="text-xs text-gray-400">Thank you for your business! — Generated by SmartBiz</p>
        </div>
      </div>
    </div>
  );
}
